Repository Rarity-Extended/RarityExtended, pull requests merged in 2021-09, with the labels that each got.

#9 Feature/claim gold
  contexts/useRarity.js
  package.json
  pages/index.js
  pages/tavern.js
  public/avatar/banker.png
  style/Default.css
  tailwind.config.js
  utils/actions.js
  yarn.lock
Labels: enhancement

#10 Feature/mobile support
  components/ModalLogin.js
  components/Navbar.js
  contexts/useWeb3.js
  pages/_app.js
  pages/index.js
  pages/tavern.js
  style/Default.css
Labels: enhancement

#11 Feature/Dungeon The Cellar & FTM Vault
  components/Chevron.js
  components/DialogBox.js
  components/Navbar.js
  components/Typer.js
  contexts/useDungeonsTheCellar.js
  contexts/useRarity.js
  hook/useEventListener.js
  hook/useKeyPress.js
  next.config.js
  package.json
  pages/_app.js
  pages/dungeons/the-cellar.js
  pages/index.js
  pages/tavern.js
  pages/tavern/index.js
  public/avatar/facu.gif
  public/back/barbarian.png
  public/back/bard.png
  public/back/cleric.png
  public/back/druid.png
  public/back/fighter.png
  public/back/monk.png
  public/back/paladin.png
  public/back/ranger.png
  public/back/rogue.png
  public/back/sorcerer.png
  public/back/wizard.png
  public/dungeons/rat.gif
  public/dungeons/rat_dead.png
  style/Default.css
  tailwind.config.js
  utils/actions.js
  utils/dungeonTheCellar.abi.js
Labels: enhancement

#18 Feature/darkmode
  components/DialogBox.js
  components/ModalLogin.js
  components/Navbar.js
  contexts/useUI.js
  pages/404.js
  pages/_app.js
  pages/_document.js
  pages/dungeons/the-cellar.js
  pages/index.js
  pages/tavern/index.js
  public/avatar/facu.png
  style/Default.css
  tailwind.config.js
Labels: enhancement

#23 Feature/Barbarian skin update
  pages/dungeons/the-cellar.js
  pages/index.js
  pages/tavern/index.js
  public/back/barbarian.png
  public/back/barbarian.svg
  public/front/barbarian.svg
Labels: enhancement

#21 Feature/Fix blank page
  contexts/useRarity.js
  pages/_app.js
  pages/index.js
  pages/tavern/index.js
  sections/SectionNoAdventurer.js
  sections/SectionNoWallet.js
  sections/SectionRecruit.js
  tailwind.config.js
  utils/classList.js
Labels: bug

#22 Feature/Loader & wallet management
  components/Footer.js
  contexts/useWeb3.js
  hook/useClientEffect.js
  package.json
  pages/_app.js
  pages/dungeons/the-cellar.js
  pages/tavern/index.js
  utils/actions.js
  utils/classNameMapping.js
  yarn.lock
Labels: bug

#34 Feature/typo
  pages/index.js
  pages/town/tavern/index.js
  utils/actions.js
Labels: bug

#35 Feature/ZapVault address
  next.config.js
Labels: enhancement

#32 fix: only switch chain when in focus
  contexts/useWeb3.js
  hook/useWindowInFocus.js
  pages/_app.js
Labels: enhancement

#40 Fix/Rat fight revert
  contexts/useRarity.js
  contexts/useWeb3.js
  utils/actions.js
  yarn.lock
Labels: bug

#38 Feature/community stuff
  .gitignore
  .vscode/settings.json
  components/Adventurer.js
  components/Chevron.js
  components/DialogBox.js
  components/FlyoutMenu.js
  components/Footer.js
  components/ModalLogin.js
  components/Navbar.js
  components/Typer.js
  contexts/useDungeonsTheCellar.js
  contexts/useRarity.js
  contexts/useUI.js
  contexts/useWeb3.js
  hook/useClientEffect.js
  hook/useEventListener.js
  hook/useKeyPress.js
  hook/useLocalStorage.js
  hook/useWindowInFocus.js
  pages/404.js
  pages/_app.js
  pages/_document.js
  pages/dungeons/the-cellar.js
  pages/index.js
  pages/town/bank.js
  pages/town/blacksmith.js
  pages/town/market.js
  pages/town/quest.js
  pages/town/tavern/index.js
  sections/SectionDungeonTheCellar.js
  sections/SectionDungeonTheForest.js
  sections/SectionNoAdventurer.js
  sections/SectionNoWallet.js
  sections/SectionRecruit.js
  style/Default.css
  utils/actions.js
  utils/classList.js
  utils/classNameMapping.js
  utils/dungeonTheCellar.abi.js
  utils/index.js
  utils/items.js
  utils/rarity.abi.js
  utils/rarityAttr.abi.js
  utils/rarityGold.abi.js
Labels: enhancement

#43 Feature/Lara Text update
  pages/town/quest.js
  sections/SectionDungeonTheForest.js
Labels: enhancement

#44 Feature/skills
  components/Adventurer.js
  components/Chevron.js
  components/DialogBox.js
  components/FlyoutMenu.js
  components/ModalLogin.js
  contexts/useRarity.js
  lib/skills.js
  next.config.js
  pages/index.js
  public/skills/appraise.png
  public/skills/balance.png
  public/skills/bluff.png
  public/skills/climb.png
  public/skills/concentration.png
  public/skills/craft.png
  public/skills/decipher_script.png
  public/skills/diplomacy.png
  public/skills/disable_device.png
  public/skills/disguise.png
  public/skills/escape_artist.png
  public/skills/forgery.png
  public/skills/gather_information.png
  public/skills/handle_animal.png
  public/skills/heal.png
  public/skills/hide.png
  public/skills/intimidate.png
  public/skills/jump.png
  public/skills/knowledge.png
  public/skills/listen.png
  public/skills/move_silently.png
  public/skills/open_lock.png
  public/skills/perform.png
  public/skills/profession.png
  public/skills/ride.png
  public/skills/search.png
  public/skills/sense_motive.png
  public/skills/sleight_of_hand.png
  public/skills/speak_language.png
  public/skills/spellcraft.png
  public/skills/spot.png
  public/skills/survival.png
  public/skills/swim.png
  public/skills/tumble.png
  public/skills/use_magic_device.png
  public/skills/use_rope.png
  sections/SectionDungeonTheForest.js
  sections/SectionRecruit.js
  style/Default.css
  tailwind.config.js
  utils/actions.js
  utils/classList.js
  utils/raritySkills.abi.js
  utils/skillList.js
Labels: enhancement

#49 BugFix/Update FTM API
  pages/town/tavern/index.js
Labels: bug

#24 feature/Guild Page for fast actions
  .node-version
  components/FlyoutMenu.js
  pages/town/guild-house.js
  public/menu/guild house.png
Labels: enhancement

#56 Feature/fixes
  contexts/useRarity.js
  pages/_app.js
  pages/index.js
  pages/town/guild-house.js
  pages/town/tavern/index.js
  public/avatar/janet.gif
  public/avatar/janet.png
  style/Default.css
Labels: bug

#57 Feature/clean
  components/Typer.js
  contexts/useDungeonsTheCellar.js
  contexts/useRarity.js
  pages/index.js
  pages/town/tavern/index.js
  sections/SectionCharacterSheet/Attributes.js
  sections/SectionCharacterSheet/Balloon.js
  sections/SectionCharacterSheet/Inventory.js
  sections/SectionCharacterSheet/Skills.js
  sections/SectionCharacterSheet/index.js
  sections/SectionDungeonTheCellar.js
  sections/SectionDungeonTheForest.js
  sections/SectionRecruit.js
  utils/abi/dungeonTheCellar.abi.js
  utils/abi/rarity.abi.js
  utils/abi/rarityAttr.abi.js
  utils/abi/rarityGold.abi.js
  utils/abi/raritySkills.abi.js
  utils/abi/readme.md
  utils/actions.js
  utils/codex/classes.js
  utils/codex/items.js
  utils/codex/readme.md
  utils/codex/skills.js
  utils/codex/tavernNews.json
  utils/items.js
  utils/libs/rarity.js
  utils/libs/raritySkills.js
  utils/libs/readme.md
Labels: enhancement

#69 BugFixes/Github Issues
  components/Footer.js
  pages/_app.js
  pages/dungeons/the-cellar.js
  pages/dungeons/the-forest.js
  style/Default.css
  utils/actions.js
Labels: bug

#76 Feature/Level Progress
  sections/SectionCharacterSheet/index.js
  style/Default.css
Labels: enhancement

#73 Feature/Bank
  components/DialogBox.js
  next.config.js
  pages/town/bank.js
  pages/town/tavern/index.js
  public/avatar/ivan.gif
  utils/actions.js
Labels: enhancement

#86 Update tavernNews.json
  utils/codex/tavernNews.json
Labels: documentation, enhancement

#84 Feature/Monk skin update
  pages/dungeons/the-cellar.js
  pages/dungeons/the-forest.js
  public/back/monk.png
  public/back/monk.svg
  public/front/monk.svg
  sections/SectionCharacterSheet/index.js
  utils/codex/classes.js
Labels: enhancement
